document.addEventListener('DOMContentLoaded',()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const companies={
  chemicals:{sector:'Chemicals',title:'Maskura Chemicals',intro:'Connecting industrial customers with reliable chemical sourcing, responsive service and international supplier relationships.',overviewTitle:'Commercial chemical expertise for the Bangladesh market.',overview:['Maskura Chemicals supports customers through product sourcing, supplier coordination and practical market knowledge.','Its role within the group creates natural links with logistics and international trading.'],caps:[['Product Sourcing','Identify suitable products through an international supplier network.'],['Supplier Coordination','Support communication, commercial alignment and documentation.'],['Market Support','Help customers manage product requirements and supply planning.']],facts:[['Primary Market','Bangladesh'],['Role','Industrial supply'],['Group Link','Logistics & trading']]},
  logistics:{sector:'Logistics',title:'Maskura Logistics',intro:'Coordinating freight and supply-chain movement across the trade lanes that connect Maskura’s markets.',overviewTitle:'Logistics built around visibility and dependable execution.',overview:['Maskura Logistics helps organise the movement of goods through international freight networks.','The business works closely with sourcing, trading and e-commerce operations.'],caps:[['Freight Coordination','Coordinate international shipments across relevant trade lanes.'],['Shipment Visibility','Maintain clear communication throughout the movement process.'],['Trade Support','Assist with operational details and shipment documentation.']],facts:[['Network','International'],['Role','Goods movement'],['Group Link','Trade & commerce']]},
  store:{sector:'E-Commerce',title:'Maskura Store',intro:'A United Kingdom e-commerce operation focused on practical products and dependable online customer experiences.',overviewTitle:'Digital retail shaped by real customer needs.',overview:['Maskura Store combines product selection, digital merchandising, fulfilment coordination and customer service.','It also provides a live environment for the group’s technology and marketing capabilities.'],caps:[['Online Retail','Build and operate focused digital storefronts.'],['Customer Experience','Improve discovery, purchasing clarity and communication.'],['Commerce Operations','Coordinate inventory, fulfilment and service.']],facts:[['Primary Market','United Kingdom'],['Role','Digital retail'],['Group Link','Tech & marketing']]},
  tech:{sector:'Technology',title:'Maskura Tech',intro:'Building digital products, automations and infrastructure that help businesses work more effectively.',overviewTitle:'Technology designed around useful business outcomes.',overview:['Maskura Tech develops systems that improve operations, customer experiences and decision-making.','Its work ranges from websites and software to automation and connected internal tools.'],caps:[['Software Solutions','Build digital tools around specific workflows and customer needs.'],['Automation','Reduce repetitive work and connect business processes.'],['Digital Infrastructure','Create reliable foundations for websites, applications and data.']],facts:[['Delivery','Digital products'],['Role','Technology enablement'],['Group Link','All companies']]},
  ideospark:{sector:'Digital Marketing',title:'IdeoSpark',intro:'Helping businesses grow through brand strategy, digital experiences, performance marketing and creative execution.',overviewTitle:'Strategy and execution connected in one growth partner.',overview:['IdeoSpark supports businesses that need clearer positioning, stronger digital experiences and more effective marketing.','The team combines strategic thinking with hands-on creative and performance delivery.'],caps:[['Brand & Strategy','Clarify positioning, messages and brand direction.'],['Digital Experience','Design websites, content and customer journeys.'],['Growth Marketing','Plan and execute relevant digital campaigns.']],facts:[['Discipline','Marketing & brand'],['Role','Growth enablement'],['Group Link','Commerce & tech']]},
  hawari:{sector:'International Trading',title:'Hawari International',intro:'Developing cross-border commercial relationships between suppliers, buyers and international markets.',overviewTitle:'International trade supported by trusted relationships.',overview:['Hawari International identifies and develops trading opportunities across borders.','Its international perspective complements the group’s sourcing and logistics capabilities.'],caps:[['Trade Development','Identify viable products, partners and opportunities.'],['Partner Coordination','Support communication between buyers and sellers.'],['Commercial Support','Help structure the steps required to move opportunities forward.']],facts:[['Network','Cross-border'],['Role','International trade'],['Group Link','Sourcing & logistics']]}
 };
 const stories={
  'connected-commerce':['Featured Insight','Why connected capabilities matter in cross-border commerce.','Sourcing, logistics, technology and customer experience create more value when they operate as one connected system.','<p class="lead">Cross-border commerce is often described as a sequence. In practice, every stage affects every other stage.</p><p>A sourcing decision changes freight requirements. A logistics delay changes customer communication. A weak digital system makes both problems harder to see.</p><h2>Connection improves speed</h2><p>When teams do not rebuild context at every handover, decisions happen faster and communication becomes clearer.</p><blockquote>The strongest commercial systems are clear between functions, not only efficient within them.</blockquote><h2>Visibility improves judgement</h2><p>Connected information helps teams distinguish temporary issues from structural ones and choose the right response.</p>'],
  'human-automation':['Innovation','Designing automation around people, not just processes.','Useful automation removes friction while keeping judgement, accountability and adoption at the centre.','<p class="lead">The value of automation is not the number of steps it removes. It is the improvement it creates for people and customers.</p><h2>Begin with the real bottleneck</h2><p>Map where decisions happen so automation does not make a workflow faster but less reliable.</p><h2>Measure adoption</h2><p>Usage, exception rates and team feedback are all part of performance.</p>'],
  'logistics-visibility':['Perspective','Visibility is becoming a core logistics capability.','Movement matters, but timely and understandable information increasingly shapes service quality.','<p class="lead">Customers experience logistics through information as much as through transport.</p><h2>Information changes planning</h2><p>Accurate status information allows teams to prepare, manage inventory and communicate downstream.</p><h2>Clarity beats volume</h2><p>The most useful update explains what changed, what it means and what happens next.</p>'],
  'coherent-group':['Group','What makes a diversified business group coherent?','Shared standards and capabilities strengthen specialist businesses without diluting focus.','<p class="lead">Diversification creates resilience only when the portfolio has a reason to work together.</p><h2>Shared philosophy</h2><p>A common decision standard gives different companies a recognisable operating identity.</p><h2>Focused leadership</h2><p>Each company still needs a specific market, accountable leadership and clear performance measures.</p>'],
  'ecommerce-trust':['Commerce','Building trust into the online customer journey.','Clarity and consistency reduce uncertainty before, during and after an online purchase.','<p class="lead">Online customers make decisions without holding the product or speaking directly to a salesperson.</p><h2>Make the offer understandable</h2><p>Clear product information, expectations and policies reduce hesitation.</p><h2>Design for difficult moments</h2><p>Easy access to help and honest communication can protect the relationship.</p>'],
  'local-context':['International','Local context remains essential in global trade.','International reach creates options, but local knowledge determines which options are practical.','<p class="lead">An opportunity can look attractive at a distance and become complicated when it meets local requirements and expectations.</p><h2>Markets interpret value differently</h2><p>Pricing, service, product fit and trust carry different weight across markets.</p><h2>Global standards still matter</h2><p>The strongest model combines consistent standards with flexibility to work in context.</p>']
 };
 const coTitle=document.querySelector('#coTitle');if(coTitle){const k=new URLSearchParams(location.search).get('co')||'chemicals',d=companies[k]||companies.chemicals;document.title=d.title+' | Maskura Group';coTitle.textContent=d.title;document.querySelector('#coSector').textContent=d.sector;document.querySelector('#coCrumb').textContent=d.title;document.querySelector('#coIntro').textContent=d.intro;document.querySelector('#coOverviewTitle').textContent=d.overviewTitle;document.querySelector('#coOverview').innerHTML=d.overview.map(x=>'<p>'+x+'</p>').join('');document.querySelector('#coCaps').innerHTML=d.caps.map((x,i)=>'<article class="info-card reveal"><span>0'+(i+1)+'</span><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join('');document.querySelector('#coFacts').innerHTML=d.facts.map(x=>'<article class="fact-card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></article>').join('')}
 const storyTitle=document.querySelector('#storyTitle');if(storyTitle){const k=new URLSearchParams(location.search).get('story')||'connected-commerce',d=stories[k]||stories['connected-commerce'];document.title=d[1]+' | Maskura Group';document.querySelector('#storyCategory').textContent=d[0];storyTitle.textContent=d[1];document.querySelector('#storyDeck').textContent=d[2];document.querySelector('#storyBody').innerHTML=d[3]}
 document.querySelectorAll('#year').forEach(x=>x.textContent=new Date().getFullYear());
 const path=location.pathname.split('/').pop()||'index.html',active=path==='company-details.html'?'companies.html':path==='news-detail.html'?'news.html':path;document.querySelectorAll('.main-nav a').forEach(a=>{if(a.getAttribute('href')===active)a.setAttribute('aria-current','page')});
 const header=document.querySelector('#siteHeader');if(header){const u=()=>header.classList.toggle('scrolled',scrollY>8);u();addEventListener('scroll',u,{passive:true})}
 const toggle=document.querySelector('#navToggle'),nav=document.querySelector('#mainNav');if(toggle&&nav){const close=()=>{nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('nav-open')};toggle.onclick=()=>{const o=nav.classList.toggle('is-open');toggle.setAttribute('aria-expanded',o);document.body.classList.toggle('nav-open',o)};nav.querySelectorAll('a').forEach(a=>a.onclick=close);addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
 const els=document.querySelectorAll('.reveal');if(reduced)els.forEach(e=>e.classList.add('is-visible'));else if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach((e,i)=>{if(e.isIntersecting){setTimeout(()=>e.target.classList.add('is-visible'),i*35);io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -45px'});els.forEach(e=>io.observe(e))}else els.forEach(e=>e.classList.add('is-visible'));
 document.querySelectorAll('[data-counter]').forEach(el=>{const run=()=>{const target=+el.dataset.counter,start=performance.now();if(reduced){el.textContent=target;return}const step=n=>{const p=Math.min((n-start)/1400,1);el.textContent=Math.round((1-Math.pow(1-p,3))*target);if(p<1)requestAnimationFrame(step)};requestAnimationFrame(step)};if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){run();io.disconnect()}},{threshold:.6});io.observe(el)}else run()});
 document.querySelectorAll('.demo-form,#contactForm').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const n=f.querySelector('.form-note')||document.querySelector('#formNote');if(n)n.textContent='Thank you — your message has been received. This demo form is ready to connect to your email or backend service.';f.reset()}));
});
